project 'Video Share Location.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Video Share Location' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  #pod 'GooglePlaces'
  #pod 'GooglePlacesAPI
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  # Pods for Video Share Location
end