project 'WeShick.xcodeproj'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'WeShick' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  # Pods for WeShick
end